/*
 * CadastroOperador.java
 *
 * Created on 8 de Setembro de 2016, 23:31
 */

package br.com.ecf;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import br.com.ecf.model.FuncionarioBean;
import br.com.ecf.model.FuncionarioDAO;

import javax.swing.GroupLayout;

/**
 *
 * @author  Frederico
 */
public class CadastroOperador extends javax.swing.JFrame {
    
    /** Creates new form CadastroOperador */
    public CadastroOperador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        tf_login = new javax.swing.JTextField();
        tf_senha = new javax.swing.JTextField();
        tf_celular = new javax.swing.JTextField();
        cb_acesso = new javax.swing.JComboBox();
        botao_cadastrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Cadastro de Operador(a)");

        jLabel2.setText("Nome:");

        jLabel3.setText("Login:");

        jLabel4.setText("Senha:");

        jLabel5.setText("Celular:");

        cb_acesso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "operador", "gerente" }));

        botao_cadastrar.setText("Cadastrar");
        botao_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Acesso:");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(20)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createParallelGroup(Alignment.LEADING)
        					.addComponent(jLabel3)
        					.addComponent(jLabel4)
        					.addComponent(jLabel5)
        					.addComponent(jLabel2))
        				.addComponent(jLabel6))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel1)
        					.addContainerGap())
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(tf_nome, GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        						.addComponent(tf_celular, GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        						.addComponent(tf_senha, GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        						.addComponent(tf_login, GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(cb_acesso, GroupLayout.PREFERRED_SIZE, 155, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(botao_cadastrar)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jButton2)))
        					.addGap(210))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addGap(27)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(tf_nome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(tf_login, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(tf_senha, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel5)
        				.addComponent(tf_celular, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(cb_acesso, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(botao_cadastrar)
        				.addComponent(jButton2)
        				.addComponent(jLabel6))
        			.addContainerGap(195, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
    {
        //cadastrar operadores
    	FuncionarioBean f = new FuncionarioBean();
    	f.setNome(tf_nome.getText());
    	f.setLogin(tf_login.getText());
    	f.setSenha(tf_senha.getText());
    	f.setCelular(tf_celular.getText());
    	f.setCargo((String) cb_acesso.getSelectedItem());
    	FuncionarioDAO fd = new FuncionarioDAO();
    	fd.incluir(f);
    	tf_nome.setText("");
    	tf_login.setText("");
    	tf_senha.setText("");
    	tf_celular.setText("");
    	cb_acesso.setSelectedIndex(0);
    	dispose();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    	tf_nome.setText("");
    	tf_login.setText("");
    	tf_senha.setText("");
    	tf_celular.setText("");
    	cb_acesso.setSelectedIndex(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroOperador().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify
    private javax.swing.JComboBox cb_acesso;
    private javax.swing.JButton botao_cadastrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tf_celular;
    private javax.swing.JTextField tf_login;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_senha;
    // End of variables declaration
    
}
