/*
 * ControleEstoque.java
 *
 * Created on 15 de Setembro de 2016, 14:29
 */

package br.com.ecf;
import java.awt.AWTEvent;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import br.com.ecf.model.ProdutoBean;
import br.com.ecf.model.ProdutoDAO;
import javax.swing.JLabel;
import java.awt.Font;

/**
 *
 * @author  Frederico
 */
public class ControleEstoque extends javax.swing.JFrame {
    
	 
    /** Creates new form ControleEstoque */
    public ControleEstoque()
    {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botao_cadastrar_produto = new javax.swing.JButton();
        botao_cadastrar_produto.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        	}
        });
        botao_mais_vendidos = new javax.swing.JButton();
        botao_mais_vendidos.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        	}
        });
        botao_nao_vendidos = new javax.swing.JButton();
        botao_nao_vendidos.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        	}
        });
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_produtos = new javax.swing.JTable();
        botao_qtd_minima = new javax.swing.JButton();
        botao_qtd_minima.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent arg0)
        {
        	String [] args = new String [1];
        	args[0] = "quantidade minima";
        	ProdutosEmQuantidadeMinima.main(args);
        }
        });
        botao_qtd_minima.setSize(46, 46);
        tf_pesquisar = new javax.swing.JTextField();
        botao_pesquisar = new javax.swing.JButton();
        botao_pesquisar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0)//botao pesquisar
        	{
        		pesquisar_produto();
        	}
        });
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FR Sistemas - Controle de estoque V. 1.0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Controle de estoque");
        //System.getProperty("user.dir") + "\\src\\imagens\\"
        botao_cadastrar_produto.setIcon(new ImageIcon("C:\\workspace\\ecftef\\src\\imagens\\cadastrar_produto.gif")); // NOI18N
        botao_cadastrar_produto.setText("Cadastrar produto");

        botao_mais_vendidos.setIcon(new ImageIcon("C:\\workspace\\ecftef\\src\\imagens\\mais_vendidos.gif")); // NOI18N
        botao_mais_vendidos.setText("Mais vendidos");

        botao_nao_vendidos.setIcon(new ImageIcon("C:\\workspace\\ecftef\\src\\imagens\\nao_vendidos.gif")); // NOI18N
        botao_nao_vendidos.setText("Não vendidos");
        
        tabela_produtos.setModel(new DefaultTableModel(
        	new Object[][] {
        	},
        	new String[] {
        		"C\u00F3digo", "Descri\u00E7\u00E3o", "Valor de Compra", "Valor de venda", "Qtd em Estoque", "Qtd M\u00EDnima"
        	}
        ));
        tabela_produtos.getColumnModel().getColumn(0).setPreferredWidth(120);
        tabela_produtos.getColumnModel().getColumn(1).setPreferredWidth(271);
        tabela_produtos.getColumnModel().getColumn(2).setPreferredWidth(130);
        tabela_produtos.getColumnModel().getColumn(3).setPreferredWidth(110);
        tabela_produtos.getColumnModel().getColumn(4).setPreferredWidth(120);
        tabela_produtos.getColumnModel().getColumn(5).setPreferredWidth(120);
        jScrollPane1.setViewportView(tabela_produtos);

        botao_qtd_minima.setIcon(new ImageIcon("C:\\workspace\\ecftef\\src\\imagens\\qtd_minima.gif")); // NOI18N
        botao_qtd_minima.setText("Quantidade mínima");

        botao_pesquisar.setVisible(false);
        jLabel2.setText("FR Sistemas - Telefone: 61 99565 - 0322");
       
        JButton botao_sair = new JButton("Sair");
        botao_sair.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent arg0)//BOTAO SAIR ************
        {
        	dispose();
        	//String [] args = new String[1];
        	//args[0] = "chamando login";
        	//Painel.main(args);
        }
        });
        botao_sair.setIcon(new ImageIcon("C:\\workspace\\ecftef\\src\\imagens\\sair.gif"));
        
        JLabel lblPesquisaDeProdutos = new JLabel("Pesquisa de produtos");
        lblPesquisaDeProdutos.setFont(new Font("Tahoma", Font.BOLD, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(167)
        							.addComponent(jLabel1))
        						.addGroup(layout.createSequentialGroup()
        							.addContainerGap()
        							.addComponent(botao_cadastrar_produto)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(botao_mais_vendidos, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(botao_nao_vendidos, GroupLayout.PREFERRED_SIZE, 189, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(botao_qtd_minima, GroupLayout.PREFERRED_SIZE, 173, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addContainerGap()
        							.addComponent(jLabel2)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(botao_sair))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 764, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(tf_pesquisar)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(botao_pesquisar)
        			.addGap(436))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblPesquisaDeProdutos)
        			.addContainerGap(740, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addGap(30)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(botao_sair, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(botao_qtd_minima, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        				.addComponent(botao_nao_vendidos, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        				.addComponent(botao_mais_vendidos, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        				.addComponent(botao_cadastrar_produto, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
        			.addGap(18)
        			.addComponent(lblPesquisaDeProdutos)
        			.addGap(11)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(tf_pesquisar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(botao_pesquisar))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel2)
        			.addGap(11))
        );
        //AQUI SETA A LARGURA DO LAYOUT ***********************************************
        Dimension d = new Dimension();
        d.setSize(1000,700);
        getContentPane().setLayout(layout);
        getContentPane().setSize(d.getSize());
        pack();
    }// </editor-fold>
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleEstoque().setVisible(true);
            }
        });
        
      //verificacao se apertou tecla enter
        EventQueue queue = new EventQueue()
		{
			protected void dispatchEvent(AWTEvent event)
			{
				super.dispatchEvent(event);          
					String a[];
					String tecla[];
					if (!event.paramString().equals("")) 
					{
						if  (event.paramString().substring(0, 5).equals("KEY_P"))
						{
							a = event.paramString().split(",");
							tecla = a[1].split("=");
							switch (Integer.parseInt(tecla[1]))
							{
								case 10: 
									botao_pesquisar.doClick();
									break;
								default:
									break;
							}
						}
					}
			}
		};
		Toolkit.getDefaultToolkit().getSystemEventQueue().push(queue);
        //fim verificacao apertou enter
    }

    public void pesquisar_produto()
    {
    	DefaultTableModel modelo = (DefaultTableModel)tabela_produtos.getModel();
    	modelo.setNumRows(0);
    	List<ProdutoBean>lista = new ArrayList<ProdutoBean>();
    	ProdutoDAO p = new ProdutoDAO();
    	ProdutoBean pb = new ProdutoBean();
    	pb.setDescricao(tf_pesquisar.getText());
    	lista = p.listarProdutos(pb.getDescricao());
    	for(ProdutoBean b : lista)
    	{
    		modelo.addRow(new Object []{
    			b.getCodigo(),
    			b.getDescricao(),
    			b.getValorCompra(),
    			formataValorVenda(b.getValorVenda()),
    			b.getEstoque(),
    			b.getEstoqueCritico()
    		});
    	}
    	tf_pesquisar.setText("");
    	tf_pesquisar.requestFocus();
    }

    public String formataValorVenda(Double v)
    {
    	String valor = String.valueOf(v);
    	int indicePonto = valor.indexOf(".");
    	int tamanho = valor.length();
    	if(tamanho - (indicePonto + 1) == 1)
    		valor += "0";
    	return valor;
    }
    // Variables declaration - do not modify
    private javax.swing.JButton botao_cadastrar_produto;
    private javax.swing.JButton botao_mais_vendidos;
    private javax.swing.JButton botao_nao_vendidos;
    private static javax.swing.JButton botao_pesquisar;
    private javax.swing.JButton botao_qtd_minima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_produtos;
    private javax.swing.JTextField tf_pesquisar;
}
