/*
 * DecisaoListaCompras.java
 *
 * Created on 24 de Setembro de 2016, 14:44
 */

package br.com.ecf;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import br.com.ecf.model.ListaDeCompraDAO;
import br.com.ecf.model.ProdutoDAO;

/**
 *
 * @author  Frederico
 */
public class DecisaoListaCompras extends javax.swing.JFrame {
    
    /** Creates new form DecisaoListaCompras */
    public DecisaoListaCompras()
    {
    	this.setLocationRelativeTo(null);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener()
        {
        	//botao OK 
        	public void actionPerformed(ActionEvent arg0)
        	{
        		ListaDeCompraDAO listadao = new ListaDeCompraDAO();
        		if(jComboBox1.getSelectedIndex() == 0)//confirmar qtd comprada
        		{
        			String quantidadeInserida = JOptionPane.showInputDialog(null, "Insira a quantidade comprada:");
        			//alterar no estoque
        			ProdutoDAO p = new ProdutoDAO();
        			p.alterarQtdEstoque(codigoT, quantidadeInserida);
        			//retirar da lista de compras
        			listadao.excluir(codigoT);
        		}
        		if(jComboBox1.getSelectedIndex() == 1)//cancelar da lista de compras
        		{
        			//retirar da lista de compras
        			listadao.excluir(codigoT);
        		}
        		
        		//ListaDeCompras.chamaLista();
        		dispose();
        		String [] args = new String[1];
        		args[0] = "chamando";
        		ListaDeCompras.main(args);
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Selecione uma opção:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Confirmar quantidade comprada", "Cancelar da lista de compras" }));

        jButton1.setText("OK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(146, 146, 146)
                            .addComponent(jComboBox1, 0, 251, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(136, 136, 136)
                            .addComponent(jLabel1))))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DecisaoListaCompras().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private static String codigoT;
    private static String quantidadeT;
    // End of variables declaration

    public static void transportador(String codigo, String quantidadeASerInserida)
    {
    	codigoT = codigo;
    	quantidadeT = quantidadeASerInserida;
    	
    }

    
}
