/*
 * Login.java
 *
 * Created on 8 de Setembro de 2016, 22:54
 */

package br.com.ecf;

import java.awt.AWTEvent;
import java.awt.EventQueue;
import java.awt.Toolkit;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.Date;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import br.com.ecf.model.AcessoBean;
import br.com.ecf.model.AcessoDAO;
import br.com.ecf.model.EntradaSaidaOperadoresBean;
import br.com.ecf.model.FuncionarioBean;
import br.com.ecf.model.FuncionarioDAO;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Color;

/**
 *
 * @author  Frederico
 */
public class Login extends javax.swing.JFrame {

    public Login()
    {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_login = new javax.swing.JTextField();
        tf_senha = new javax.swing.JPasswordField();
        tf_senha.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent arg0)
        	{
        		 //efetuaLogin();
        	}
        });
        botao_login = new javax.swing.JButton();
        botao_cancelar = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FR Sistemas - Frente de caixa e Controle de estoque");
        setMinimumSize(new java.awt.Dimension(800, 600));
        String caminho = System.getProperty("user.dir") + "\\src\\imagens\\";
    	String imagem = caminho + "logomarca.png";
    	ImageIcon img = new ImageIcon(imagem);
        jLabel1.setIcon(img); // NOI18N

        jLabel2.setText("LOGIN:");

        jLabel3.setText("SENHA:");

        botao_login.setText("Logar");
        botao_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_loginActionPerformed(evt);
            }
        });

        botao_cancelar.setText("Limpar");
        botao_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cancelarActionPerformed(evt);
            }
        });
        
        JLabel lblNewLabel = new JLabel("Sistema Frente de caixa e Controle de estoque");
        lblNewLabel.setForeground(Color.BLUE);
        lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(187)
        					.addComponent(jLabel1))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(230)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel2)
        						.addComponent(jLabel3))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(tf_senha)
        						.addComponent(tf_login, GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(botao_login)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(botao_cancelar))))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(111)
        					.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 480, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addComponent(jLabel1)
        			.addGap(34)
        			.addComponent(lblNewLabel)
        			.addPreferredGap(ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(tf_login, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(tf_senha, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(botao_login)
        				.addComponent(botao_cancelar))
        			.addGap(93))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void botao_loginActionPerformed(java.awt.event.ActionEvent evt)
    {
    	//++contadorDeLogin;
    	//if(contadorDeLogin == 1)
    		efetuaLogin();
    }

    public String formatarData(Date data)
    {
    	String dia = "";
    	String mes = "";
    	String ano = "";
    	ano = String.valueOf(1900 + data.getYear());
    	if(data.getDate() < 10)
    		dia = "0" + String.valueOf(data.getDate());
    	else
    		dia = String.valueOf(data.getDate());
    	if(data.getMonth() + 1 < 10)
    		mes = "0" + String.valueOf(data.getMonth() +1);
    	return dia + "/" + mes + "/" + ano;
    }

    public void efetuaLogin()
    {
    	String login = tf_login.getText();
    	String senha = tf_senha.getText();
    	FuncionarioBean f = new FuncionarioBean();
    	FuncionarioBean funcionarioPesquisado = new FuncionarioBean();
    	FuncionarioDAO func = new FuncionarioDAO();
    	f.setLogin(login);
    	f.setSenha(senha);
    	Date d = new Date();
    	String dataFormatada = formatarData(d);
    	//SimpleDateFormat df = new SimpleDateFormat("dd/m/YYYY");
    	//String dataFormatada = df.format(d);
    	funcionarioPesquisado = func.login(f);
    	if(funcionarioPesquisado.getLogin().equals(f.getLogin()) && 
    		funcionarioPesquisado.getSenha().equals(f.getSenha()) &&
    		funcionarioPesquisado.getCargo().equals("admin"))
    	{
    		String [] args = new String[1];
    		args[0] = "Onde aparece esse texto - login?";
    		Painel.main(args);//chama o JFrame painel.
    		this.hide();//fecha form login.
    		Painel.setarUsuarioLogado(funcionarioPesquisado.getNome().toUpperCase());
    		Painel.label_data_hora.setText("Hoje é dia: " + dataFormatada);
    		Painel.setarTodosDadosUsuarioLogado(funcionarioPesquisado);
    	}
    	else if(funcionarioPesquisado.getLogin().equals(f.getLogin()) && 
        		funcionarioPesquisado.getSenha().equals(f.getSenha()) &&
        		funcionarioPesquisado.getCargo().equals("operador"))
        {
    		String [] args = new String[1];
    		args[0] = "Onde aparece esse texto - login?";
    		ViewCaixa.main(args);//chama o JFrame ViewCaixa.
    		this.hide();//fecha form login
    		ViewCaixa.setarUsuarioLogado(funcionarioPesquisado.getNome());
    		ViewCaixa.label_usuario_logado.setText("Usuário logado: " + funcionarioPesquisado.getNome().toUpperCase());
    		ViewCaixa.label_so_login.setText(funcionarioPesquisado.getNome());
    		ViewCaixa.label_data_hora.setText("Hoje é dia: " + dataFormatada);
    		//incluindo na tabela de login e logout de operadores
    		/*
    		EntradaSaidaOperadoresBean eso = new EntradaSaidaOperadoresBean();
    		eso.setNome(funcionarioPesquisado.getNome());
    		Date d1 = new Date();
    		java.sql.Date dataSQL = new java.sql.Date(d1.getYear(), d1.getMonth(), d1.getDate());
    		eso.setData(dataSQL);
    		eso.setId(funcionarioPesquisado.getCodigo());
    		FuncionarioDAO fdao = new FuncionarioDAO();
    		fdao.incluirHoraLogin(eso);
    		*/
        }
    	else
    	{
    		JOptionPane.showMessageDialog(null, "Login ou senha não encontrado. Contate o Administrador do sistema.");
    		tf_login.setText("");
    		tf_senha.setText("");
    		tf_login.requestFocus();
    	}
    	//grava a acao no banco de dados
    	AcessoDAO ad = new AcessoDAO();
    	AcessoBean ac = new AcessoBean();
    	ac.setLogin(tf_login.getText());
    	String horaDaAcao = "";
    	Date acao = new Date();
    	String validaMinutos = "";
    	if(acao.getMinutes() < 10)
    		validaMinutos = "0" + String.valueOf(acao.getMinutes());
    	else
    		validaMinutos = String.valueOf(acao.getMinutes());
    	horaDaAcao = String.valueOf(acao.getHours()) + ":" + validaMinutos;
    	ac.setHora(horaDaAcao);
    	int dia = acao.getDate();
    	int mes = acao.getMonth() ;
    	int ano = acao.getYear();
    	ac.setData(new java.sql.Date(ano,mes,dia));//<!--- TESTE! O QUE ACONTECE AQUI ?
    	ac.setAcao("ENTRADA");
    	ac.setNome(funcionarioPesquisado.getNome());
    	ad.incluir(ac);
    }

    private void botao_cancelarActionPerformed(java.awt.event.ActionEvent evt) {
        tf_login.setText("");
        tf_senha.setText("");
        tf_login.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
      //verificacao se apertou tecla enter
        EventQueue queue = new EventQueue()
		{
			protected void dispatchEvent(AWTEvent event)
			{
				super.dispatchEvent(event);          
					String a[];
					String tecla[];
					if (!event.paramString().equals("")) 
					{
						if  (event.paramString().substring(0, 5).equals("KEY_P"))
						{
							a = event.paramString().split(",");
							tecla = a[1].split("=");
							switch (Integer.parseInt(tecla[1]))
							{
								case 10: 
									botao_login.doClick();
									break;
								default:
									break;
							}
						}
					}
			}
		};
		Toolkit.getDefaultToolkit().getSystemEventQueue().push(queue);
        //fim verificacao apertou enter
    }
    
    // Variables declaration - do not modify
    private javax.swing.JButton botao_cancelar;
    private static javax.swing.JButton botao_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_login;
    private javax.swing.JPasswordField tf_senha;
}
