package br.com.ecf;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import br.com.ecf.model.AcessoBean;
import br.com.ecf.model.AcessoDAO;
import br.com.ecf.model.FuncionarioBean;

import javax.swing.JButton;

import java.awt.AWTEvent;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.util.Date;
import java.awt.event.ActionEvent;
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.Container;

/**
 *
 * @author  Frederico
 */
public class Painel extends javax.swing.JFrame
{
    
    static String nomeLogado = "";
    static JLabel label_usuario_logado = new JLabel("");
    static FuncionarioBean funcionarioPassadoPeloLogin = new FuncionarioBean();
   // static Painel p = new Painel();
    static JLabel label_data_hora = new JLabel("aa");
    public Painel()
    {
    	setTitle("FR Sistemas - Painel ");
    	 //COMENTAR O TRECHO ABAIXO APENAS PARA VISUALIZAÇÃO NO ECLIPSE *******************
    	//INICIO DO COMENTARIO
    	
    	Dimension dim = new Dimension();
         dim.width = 700;
         dim.height = 600;
    	this.setPreferredSize(dim);
    	
    	//FIM DO COMENTARIO
        initComponents();
        this.setLocationRelativeTo(null);
    }

    
    public void chama_frente_caixa()
    {
    	String [] args = new String[1];
		args[0] = "Frente de caixa";
		this.hide();
		ViewCaixa.label_usuario_logado.setText("Usuario logado: " + nomeLogado.toUpperCase());
		ViewCaixa.label_data_hora.setText(label_data_hora.getText());
		ViewCaixa.main(args);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton1.setIcon(new ImageIcon("C:\\workspace\\ecftef\\src\\imagens\\usuarios.gif"));
        jButton2 = new javax.swing.JButton();
        jButton2.setIcon(new ImageIcon("C:\\workspace\\ecftef\\src\\imagens\\sair.gif"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        String caminho = System.getProperty("user.dir") + "\\src\\imagens\\";
    	String imagem = caminho + "logomarca.png";
    	ImageIcon img = new ImageIcon(imagem);
        jLabel1.setIcon(img); // NOI18N
        
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1.setText("Cadastrar Operador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton2.setText("Sair");
      
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        
        JLabel lblUsurioLogado = new JLabel("Usuário Logado: ");
        
        JButton botao_frente_caixa = new JButton("Frente de Caixa");
        botao_frente_caixa.setIcon(new ImageIcon("C:\\workspace\\ecftef\\src\\imagens\\cadastro_cidades.gif"));
        botao_frente_caixa.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0)//botao frente de caixa
        	{
        		chama_frente_caixa();
        		
        	}
        });
        
        botao_frente_caixa.setFont(new Font("Tahoma", Font.BOLD, 14));
        
        btnAcessoDeOperadores = new JButton("Acesso de operadores");
        btnAcessoDeOperadores.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent arg0)
        {						
        	String [] args = new String[1];
        	args[0] = "chamando cadastro operadores";
        	EntradaSaidaOperadores.main(args);
        }
        });
        btnAcessoDeOperadores.setIcon(new ImageIcon("C:\\workspace\\ecftef\\src\\imagens\\cadastro_clientes.gif"));
        btnAcessoDeOperadores.setFont(new Font("Tahoma", Font.BOLD, 14));
        
        botao_controle_estoque = new JButton("Controle de estoque");
        botao_controle_estoque.setIcon(new ImageIcon("C:\\workspace\\ecftef\\src\\imagens\\controle_estoque.gif"));
        botao_controle_estoque.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0)
        	{
        		//dispose();
        		String [] args = new String[1];
        		args[0] = "controle estoque";
        		ControleEstoque.main(args);
        	}
        });
        botao_controle_estoque.setFont(new Font("Tahoma", Font.BOLD, 14));
        
        JLabel label_qtd_minima_atingida = new JLabel("ATENÇÃO!  Há produtos que atingiram a quantidade mínima!");
        label_qtd_minima_atingida.setIcon(new ImageIcon("C:\\workspace\\ecftef\\src\\imagens\\10 - Cópia.GIF"));
        label_qtd_minima_atingida.setVisible(false);
        ProdutosEmQuantidadeMinima m = new ProdutosEmQuantidadeMinima();
        botao_verificar_qtd_minima = new JButton("Verificar ");
        botao_verificar_qtd_minima.setVisible(false);
        if(m.chamaQtdMinimaPainel())
        {
        	label_qtd_minima_atingida.setVisible(true);
        	botao_verificar_qtd_minima.setVisible(true);
        }
        	
        label_qtd_minima_atingida.setForeground(Color.RED);
        label_qtd_minima_atingida.setFont(new Font("Tahoma", Font.BOLD, 14));
        
       
        botao_verificar_qtd_minima.addActionListener(new ActionListener(){
	        //botao verificar quantidade minima
        	public void actionPerformed(ActionEvent arg0)
	        {
        		String [] args = new String [1];
            	args[0] = "quantidade minima";
            	ProdutosEmQuantidadeMinima.main(args);
	        }
        });
        botao_verificar_qtd_minima.setForeground(Color.BLUE);
        botao_verificar_qtd_minima.setFont(new Font("Tahoma", Font.BOLD, 14));
        
        JButton botao_lista_compras = new JButton("Lista de compras");
        
        botao_lista_compras.addActionListener(new ActionListener()
        {
        	//BOTAO LISTA DE COMPRAS
        	public void actionPerformed(ActionEvent arg0)
        	{
        		String []args = new String[1];
        		args[0] = "c";
        		ListaDeCompras.main(args);
        	}
        });
        botao_lista_compras.setIcon(new ImageIcon("C:\\workspace\\ecftef\\src\\imagens\\novo_registro.gif"));
        botao_lista_compras.setFont(new Font("Tahoma", Font.BOLD, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel1)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(lblUsurioLogado)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(label_usuario_logado))
        						.addComponent(label_data_hora)))
        				.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        					.addComponent(jButton1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(botao_frente_caixa, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(btnAcessoDeOperadores, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(botao_controle_estoque, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
        				.addComponent(botao_verificar_qtd_minima, GroupLayout.PREFERRED_SIZE, 231, GroupLayout.PREFERRED_SIZE)
        				.addComponent(label_qtd_minima_atingida)
        				.addComponent(botao_lista_compras, GroupLayout.PREFERRED_SIZE, 233, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(824, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lblUsurioLogado)
        						.addComponent(label_usuario_logado))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(label_data_hora)))
        			.addGap(18)
        			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(botao_frente_caixa, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        			.addGap(5)
        			.addComponent(btnAcessoDeOperadores, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(botao_controle_estoque, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(botao_lista_compras, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
        			.addGap(47)
        			.addComponent(label_qtd_minima_atingida)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(botao_verificar_qtd_minima, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(83, Short.MAX_VALUE))
        );
      
        getContentPane().setLayout(layout);
        pack();
    }// init components

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	String [] args = new String[1];
		args[0] = "Cadastro de Operadores";
    	CadastroOperador.main(args);
    }

    //LOGOUT
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        this.hide();
        String [] args = new String[1];
		args[0] = "FR Sistemas - Login";
        Login.main(args);
      //grava a acao no banco de dados
    	AcessoDAO ad = new AcessoDAO();
    	AcessoBean ac = new AcessoBean();
    	ac.setLogin(funcionarioPassadoPeloLogin.getLogin());
    	String horaDaAcao = "";
    	String validaMinutos = "";
    	Date acao = new Date();
    	//horaDaAcao = String.valueOf(acao.getHours()) + ":" + String.valueOf(acao.getMinutes());
    	if(acao.getMinutes() < 10)
    		validaMinutos = "0" + String.valueOf(acao.getMinutes());
    	else
    		validaMinutos = String.valueOf(acao.getMinutes());
    	horaDaAcao = String.valueOf(acao.getHours()) + ":" + validaMinutos;
    	
    	ac.setHora(horaDaAcao);
    	int dia = acao.getDate();
    	int mes = acao.getMonth() ;
    	int ano = acao.getYear();
    	ac.setData(new java.sql.Date(ano,mes,dia));
    	ac.setAcao("SAÍDA");
    	ac.setNome(label_usuario_logado.getText().toLowerCase());
    	ad.incluir(ac);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel().setVisible(true);
            }
        });
        /*
      //verificacao se apertou tecla enter
        EventQueue queue = new EventQueue()
		{
			protected void dispatchEvent(AWTEvent event)
			{
				super.dispatchEvent(event);          
					String a[];
					String tecla[];
					if (!event.paramString().equals("")) 
					{
						if  (event.paramString().substring(0, 5).equals("KEY_P"))
						{
							a = event.paramString().split(",");
							tecla = a[1].split("=");
							switch (Integer.parseInt(tecla[1]))
							{
								case 65: 
									JOptionPane.showMessageDialog(null, "pqp!!!");
									break;
								default:
									break;
							}
						}
					}
			}
		};
		Toolkit.getDefaultToolkit().getSystemEventQueue().push(queue);
        //fim verificacao apertou enter
		*/
    }
    
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private JButton btnAcessoDeOperadores;
    private JButton botao_controle_estoque;
    private JButton botao_verificar_qtd_minima;
    // End of variables declaration

    public static void setarUsuarioLogado(String nome)
    {
    	nomeLogado = nome;
    	label_usuario_logado.setVisible(true);
    	label_usuario_logado.setText(nomeLogado);
    }

    public static void setarTodosDadosUsuarioLogado(FuncionarioBean f)
    {
    	funcionarioPassadoPeloLogin = f;
    }
}
